[package]
name = "orbis"
version = "1.0.0"
description = "Orbis concept maps"
authors = ["Arvindh Sundar"]
license-file = "../LICENSE"
publish = false
edition = "2021"

[lib]
name = "orbis_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
